### ISSUE TITLE
rna_pdb_tools.py --rpr 1ehz.pdb --replace-hetatm KeyError: "C3'"

### ISSUE THREAD

**Issue by mmagnus** [mmagnus/rna-tools#135]
```
rna_pdb_tools.py --rpr 1ehz.pdb --replace-hetatm
~/opt/rasp-fd-1.0/
Traceback (most recent call last):
  File "/Users/magnus/miniconda3/bin/rna_pdb_tools.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/magnus/work/src/rna-tools/rna_tools/rna_pdb_tools.py", line 466, in <module>
    remarks = s.get_rnapuzzle_ready(args.renumber_residues, fix_missing_atoms=fix_missing_atom,
  File "/Users/magnus/work/src/rna-tools/rna_tools/rna_tools_lib.py", line 1325, in get_rnapuzzle_ready
    r_atoms = [r["C3'"], r["C2'"], r["C1'"]]
  File "/Users/magnus/miniconda3/lib/python3.8/site-packages/Bio/PDB/Entity.py", line 45, in __getitem__
    return self.child_dict[id]
KeyError: "C3'"
```

**Comment by mmagnus** [comment]
OK, this thinks that Mg is an RNA residue :/
