### ISSUE TITLE
GC SS_cons2 is not correctly parsed

### ISSUE THREAD

**Issue by mmagnus** [mmagnus/rna-tools#62]
```python
[mm] rna-search-with-a-new-alphabet$ python test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    a = RNAalignment('RF01074.txt')
  File "/home/magnus/work-src/rna-pdb-tools/rna_pdb_tools/utils/rna_alignment/rna_alignment.py", line 408, in __init__
    self.copy_ss_cons_to_all()
  File "/home/magnus/work-src/rna-pdb-tools/rna_pdb_tools/utils/rna_alignment/rna_alignment.py", line 554, in copy_ss_cons_to_all
    'Please check if all your sequences and ss lines are of the same length!')
Exception: Please check if all your sequences and ss lines are of the same length!
```

[RF01074.stockholm.txt](https://github.com/mmagnus/rna-pdb-tools/files/1604465/RF01074.stockholm.txt)

**Comment by mmagnus** [comment]
```python
at test.py
from rna_pdb_tools.utils.rna_alignment.rna_alignment import RNAalignment

a = RNAalignment('RF01074.txt')
print(a.tail())
print(a.ss_cons)
```
