### ISSUE TITLE
Handle input/K.pdb

### ISSUE THREAD

**Issue by mmagnus** [mmagnus/rna-tools#71]
```
[mm] rna_pdb_tools$ git:(pre-release) ✗ rna_pdb_toolsx.py --no_hr --rpr input/K.pdb
Traceback (most recent call last):
  File "/home/magnus/work-src/rna-pdb-tools/bin/rna_pdb_toolsx.py", line 320, in <module>
    verbose=args.verbose)
  File "/Users/magnus/work-src/rna-pdb-tools/rna_pdb_tools/rna_pdb_tools_lib.py", line 1078, in get_rnapuzzle_ready
    r_atoms = [r["O4'"], r["C4'"], r["C3'"]]
  File "/usr/local/lib/python2.7/site-packages/Bio/PDB/Entity.py", line 41, in __getitem__
    return self.child_dict[id]
KeyError: "O4'"
```

**Comment by mmagnus** [comment]
works with v3.6.1
```
(py37) [mx] rna_tools$ git:(master) ✗ rna_pdb_toolsx.py --no-hr --rpr input/K.pdb
REMARK 250 Hetatom to be removed from file: <Residue CCC het=H_CCC resseq=89 icode= >
REMARK 250 Hetatom to be removed from file: <Residue  NA het=H_ NA resseq=121 icode= >
REMARK 250 Hetatom to be removed from file: <Residue  NA het=H_ NA resseq=122 icode= >
REMARK 250 Hetatom to be removed from file: <Residue   K het=H_  K resseq=123 icode= >
REMARK 250 Hetatom to be removed from file: <Residue   K het=H_  K resseq=124 icode= >
REMARK 250 Hetatom to be removed from file: <Residue   K het=H_  K resseq=125 icode= >
REMARK 250 Hetatom to be removed from file: <Residue  MG het=H_ MG resseq=101 icode= >
REMARK 250 Hetatom to be removed from file: <Residue  MG het=H_ MG resseq=102 icode= >
REMARK 250 Hetatom to be removed from file: <Residue  MG het=H_ MG resseq=103 icode= >
```
